### ISSUE TITLE
change mariadb config

### ISSUE THREAD

**Issue by cphubs** [yabawock/dokku-alt-mariadb#1]
How can i change mariadb config file?

I work on project with dokku-alt that my users should change common mysql settings like
Encoding - Max connections limit and ...

and in dokku-alt dokku mariadb:console:admin not working

thanks

**Comment by yabawock** [comment]
In you want to change these settings globally for all users fork the repository and make the modifications to the config file. Max connections is for the whole server. If it's per user then do it in the app using per connection settings.

**Comment by cphubs** [comment]
each user have its own server and can not change this config and rebuild image again!
if possible make it as volume to edit config?

**Comment by yabawock** [comment]
That's something that would need to be managed by dokku-alt. This image only provides the server. If dokku-alt were to mount a different /etc/mysql as a volume it should be possible.

**Comment by cphubs** [comment]
Ok thanks
